install.packages("shinydashboard")
install.packages("dplyr")
#install.packages("magrittr")
install.packages("ggplot2")
install.packages('tidyr')
#install.packages('scales')
#install.packages('ggridges')
install.packages('purrr')
install.packages('DT')
install.packages("remotes")
remotes::install_github("LCBC-UiO/ggseg@6f50483", build_vignettes = FALSE)

