install.packages("shiny")
install.packages("dplyr")
install.packages("magrittr")
install.packages("ggplot2")
install.packages('tidyr')
install.packages('scales')
install.packages('ggridges')
install.packages('purrr')
install.packages('DT')
install.packages("here")
install.packages("devtools")
devtools::install_github("LCBC-UiO/ggseg", build_vignettes = FALSE)

